// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcyvxgzribrqcwhmxpln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjeXZ4Z3pyaWJycWN3aG14cGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTk0MzQsImV4cCI6MjA2Njg5NTQzNH0.NKRir38Lf7j0EbGjQV8JW4BTQWMcVMjJKPQF8GdqkVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});